name: STIG & OpenSCAP CI

on:
  push:
  pull_request:

jobs:
  security-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build security image
        run: |
          docker build -t ubuntu-stig .

      - name: Run container with checks
        run: |
          docker run --name stigscan ubuntu-stig

      - name: Collect results
        run: |
          docker cp stigscan:/results ./results

      - name: Upload scan results
        uses: actions/upload-artifact@v3
        with:
          name: STIG_SCAN_RESULTS
          path: results/
