name: STIG & OpenSCAP CI

on:
  push:
  pull_request:

jobs:
  security-scan:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build security image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          tags: ubuntu-stig:latest
          load: true

      - name: Run container with checks
        run: |
          docker run --name stigscan ubuntu-stig:latest

      - name: Collect results
        run: |
          mkdir -p results
          docker cp stigscan:/results ./results

      - name: Upload scan results
        uses: actions/upload-artifact@v4
        with:
          name: STIG_SCAN_RESULTS
          path: results/
